server:
  port: 8084

spring:
  application:
    name: gateway_service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: school_route
          uri: lb://SCHOOL
          predicates:
            - Path=/schools/**
        - id: student_route
          uri: lb://STUDENT
          predicates:
            - Path=/students/**
      enabled: true
    refresh:
      enabled: true
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: false
    enabled: true